### PR TITLE
Fixed styles of table in content

### LINKED ISSUE #730: Table styles breaking in editor content
- [ ] Update `renderHTM` of tables' `extensionConfig` to support colgroup

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #730 

**Description**

- Fixed: `renderHtml()` to add `colgroups` to table content

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

File: src/components/Editor/CustomExtensions/Table/ExtensionConfig.js [hunk 1]
```diff
@@ -14,6 +14,15 @@ const Table = TiptapTable.extend({
       allowTableNodeSelection: true,
     };
   },
+  renderHTML({ node }) {
+    const colgroups = node?.content?.content?.[0]?.content?.content.map(col => [
```
Comment (AbhayVAshokan) [inline src/components/Editor/CustomExtensions/Table/ExtensionConfig.js:18]:
```suggestion
    const colgroups = node?.content?.content?.[0]?.content?.conten?t.map(col => [
```

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a please assign this PR back to me so that I can merge both PRs together.

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the changes.
