### PR TITLE
Added mentions to fixed and slash menu

### LINKED ISSUE #118: Add mentions to fixed menu and slash menu
- It may not be intuitive to realize that mentions are enabled without typing `@` character.
- Add mentions to the fixed menu and slash commands if it is active.

enhancement _t
@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #118 
- Added mentions to slash menu.
- Added mentions to the fixed menu as a dropdown.

Demo: https://vimeo.com/660657942/b70f931315

@labeebklatif _a please review.
cc: @goutham-subramanyam

### CODE REVIEW

File: lib/components/Editor/CustomExtensions/Mention/index.js [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+} from "../FixedMenu/constants";
+
+const Mentions = ({ editor, mentions, showImageInMention }) => {
+  const dropdownRef = useRef();
+
+  const handleSelectedMention = (label) => {
+    editor
+      .chain()
+      .focus()
+      .insertContent([
```
Comment (labeebklatif) [inline lib/components/Editor/CustomExtensions/Mention/index.js:20]: Instead of calling insertContent directly here, It is advisable to create custom command option for adding mentions. This is how other extensions in tiptap normally works. Please refer Variable extension for a already created custom command.

File: lib/components/Editor/CustomExtensions/Mention/index.js [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+
+  return (
+    <Dropdown
+      ref={dropdownRef}
+      customTarget={() => (
+        <button type="button" className="neeto-editor-fixed-menu__item">
+          <Email
+            size={MENU_ICON_SIZE}
+            color={
+              dropdownRef?.current?.visible
```
Comment (labeebklatif) [inline lib/components/Editor/CustomExtensions/Mention/index.js:44]: reformat this to `dropdownRef.current?.visible`. We expect `dropdownRef` to always have a `current` property.

**Comment by labeebklatif** [comment]
@AbhayVAshokan @amaldinesh7 @karthiknmenon Just want to know your opinion on https://www.loom.com/share/62d72ef5cc50416e985ab1dc7493624c

Not sure if this change was intentionally done. Let me know

**Review by labeebklatif — CHANGES_REQUESTED** [review]
@AbhayVAshokan _a Added some comments. Please have a look

**Comment by AbhayVAshokan** [comment]
> @AbhayVAshokan @amaldinesh7 @karthiknmenon Just want to know your opinion on https://www.loom.com/share/62d72ef5cc50416e985ab1dc7493624c
> 
> Not sure if this change was intentionally done. Let me know

@labeebklatif please have a look:
https://vimeo.com/661231570/bcbbfb1212


cc: @karthiknmenon, @amaldinesh7

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a please review the new changes.

File: lib/components/Editor/CustomExtensions/Mention/ExtensionConfig.js [hunk 3]
```diff
@@ -56,9 +56,36 @@ const suggestion = {
...
+  addCommands() {
+    return {
+      setMention:
+        (label) =>
+        ({ chain }) => {
+          chain()
+            .focus()
+            .insertContent([
+              {
+                type: "mention",
```
Comment (labeebklatif) [inline lib/components/Editor/CustomExtensions/Mention/ExtensionConfig.js:69]:
```suggestion
                type: this.name,
```

**Review by labeebklatif — COMMENTED** [review]
@AbhayVAshokan _a A minor suggestion. Please check.

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a please review the new changes.

**Comment by labeebklatif** [comment]
@goutham-subramanyam _a Changes LGTM. Please review the UI and merge.

**Review by goutham-subramanyam — APPROVED** [review]
LGTM.
