### PR TITLE
Added emoji picker to fixed menu

### LINKED ISSUE #85: Add emoji picker to fixed menu
Add emoji picker dropdown to the fixed menu: ref [#64 comment](https://github.com/bigbinary/neeto-editor-tiptap/pull/64#issuecomment-989123701).

@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #85 
- Added emoji picker dropdown to fixed menu.
Emoji Picker dropdown

@amaldinesh7 _a please take a look.

### CODE REVIEW

File: lib/components/Editor/CustomExtensions/FixedMenu/EmojiOption.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+                ? ICON_COLOR_ACTIVE
+                : ICON_COLOR_INACTIVE
+            }
+          />
+        </button>
+      )}
+      position="bottom-start"
+    >
+      <div className="overflow-hidden h-80">
+        <EmojiPickerMenu editor={editor} range={{}} />
```
Comment (amaldinesh7) [inline lib/components/Editor/CustomExtensions/FixedMenu/EmojiOption.js:34]: What is this range for? why is it empty?

**Review by amaldinesh7 — CHANGES_REQUESTED** [review]
@AbhayVAshokan _a I've added one comment please check it.

File: lib/components/Editor/CustomExtensions/FixedMenu/EmojiOption.js (hunk 1 above)
Comment (AbhayVAshokan) [reply lib/components/Editor/CustomExtensions/FixedMenu/EmojiOption.js:34]: The `EmojiPickerMenu` uses `range` to remove the decorator (::). Since there is no decorator involved while using via dropdown, the range is empty. Instead, I shall specify`range={{}}` as default in the component itself to avoid this confusion.

**Comment by AbhayVAshokan** [comment]
@amaldinesh7 _a please have a look.

**Comment by amaldinesh7** [comment]
LGTM!
