### PR TITLE
Fixed the issues with interfering image and text bubble menus

### LINKED ISSUE #221: Image bubble menu interfering with normal bubble menu
Screenshot 2022-04-13 at 7 56 19 PM

bug _t

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #221
- Fixed the issue where the bubble menus for image and text were interfering with each other.
Demo: https://vimeo.com/703276559/1c28b92c9c

@labeebklatif _a please review.

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a I've made the changes requested over call.

File: lib/components/Editor/CustomExtensions/BubbleMenu/TextOptions.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  options,
+  setIsInvalidLink,
+  isLinkOptionActive,
+  setIsLinkOptionActive,
+}) => {
+  const handleAnimateInvalidLink = () => {
+    setIsInvalidLink(true);
+    const timer = setTimeout(() => {
+      setIsInvalidLink(false);
+      clearTimeout(timer);
```
Comment (labeebklatif) [inline lib/components/Editor/CustomExtensions/BubbleMenu/TextOptions.js:18]: The clearTimeout here may not have any effect as this will be only evaluated after the timeout has already triggered and cleared.

**Review by labeebklatif — APPROVED** [review]
@AbhayVAshokan _a few minor suggestions. Please merge once updated
