### PR TITLE
Fixed types file

### LINKED ISSUE #588: Fix issues with types
- [ ] Refer to neetoChat and generalize tooltip types: [Composer.jsx](https://github.com/bigbinary/neeto-chat-web/blob/40e692ae5c1dbce438dc38fa6092025009687253/app/javascript/src/components/Inbox/Messenger/Composer.jsx#L267-L281).
image

- [ ] The `editor` prop in `Menu` should not be string. It should be nullable as well.

https://github.com/bigbinary/neeto-editor/blob/6c83d4be13686f19ef98152525d9efd074163740/types.d.ts#L78

- [x] The `onChangeAttachments` prop should be optional. `variables` prop should be optional. Find other optional props and make necessary changes.

- [x] Add types for `substituteVariables` method.
- [x] Add types for `isEditorOverlaysActive` method.

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #588

**Description**
Fixed: types.d.ts file

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

File: types.d.ts [hunk 1]
```diff
@@ -69,8 +69,13 @@ interface Config {
...
-interface tooltips {
-[key: string]: string;
+interface Tooltip {
+  label: string;
+  keys: string[];
+}
+
+interface Tooltips {
+  [key: string]: Tooltip;
 }
```
Comment (AbhayVAshokan) [inline types.d.ts:79]: Where is the capitalized `Tooltips` used? 
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the changes.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
1. `variables` should be optional in `EditorContent`.
2. Add `editorSecrets` to `Menu` component.

@gaagul _a please merge after these changes.
