### PR TITLE
Fixed media editor footer UI and optimized code

### LINKED ISSUE #583: The media editor footer styles are broken
image

@gaagul _a please take this up. bug _t

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #583 

**Description**

- Fixed: broken media editor footer

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

File: lib/components/Editor/MediaUploader/MediaEditor.jsx [hunk 1]
```diff
@@ -78,8 +78,12 @@ const MediaEditor = ({
...
       )}
       <div className="ne-media-editor__footer">
-        <Button disabled={isError} label="Done" onClick={handleSubmit} />
-        <Button label="Cancel" style="text" onClick={onClose} />
+        <Button
+          disabled={isError}
+          label="Save changes"
+          onClick={handleSubmit}
+        />
+        <Button label="Cancel" style="secondary" onClick={onClose} />
```
Comment (AbhayVAshokan) [inline lib/components/Editor/MediaUploader/MediaEditor.jsx:86]:
```suggestion
        <Button label="Cancel" style="text" onClick={onClose} />
```

**Review by AbhayVAshokan — APPROVED** [review]
Nice. @gaagul _a please merge after this change.
