### PR TITLE
Fix validation error disappearence when using nested names

### LINKED ISSUE #1354: Errors are not cleared for Editor component
Ref: https://sandip-mane.neetorecord.com/watch/d0e4077c0ac690844743
bug _t

### PR DESCRIPTION
**Pull request by navaneethsdk**
- Fixes #1354 

**Description**
- Handled error and touch comparison involving nested name keys

**Checklist**

- [x] ~I have made corresponding changes to the documentation.~
- [x] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

File: src/components/Editor/FormikEditor.jsx [hunk 1]
```diff
@@ -25,9 +26,15 @@ const FormikEditor = (
     const prevFormikProps = prevProps.formik;
     const nextFormikProps = nextProps.formik;
 
+    const pathParts = name.split(".");
+    const prevError = path(pathParts, prevFormikProps.errors);
+    const nextError = path(pathParts, nextFormikProps.errors);
+    const prevTouched = path(pathParts, prevFormikProps.touched);
+    const nextTouched = path(pathParts, nextFormikProps.touched);
```
Comment (navaneethsdk) [inline src/components/Editor/FormikEditor.jsx:33]: @AbhayVAshokan Please let me know if we have a better way of implementing this with a compact function. I couldn't find one in neeto-cist. Found https://lodash.com/docs/4.17.15#get, however decided to stick with Ramda respecting immutability.

Comment (AbhayVAshokan) [reply src/components/Editor/FormikEditor.jsx:33]: This looks neat. Just what I had in mind.

**Review by AbhayVAshokan — APPROVED** [review]
